### PR TITLE
Eurovelo map: Dynamic URL, geolocation button, full width, two fingers scroll only, save filter state on zoom

### PR DESCRIPTION
**Pull request by uniorunr**
Live Demo - https://eurovelo-demo-map.netlify.com/

Features:
1) Dynamic URL (zoom and coordinates as parameters)
2) Added button to define user geolocation 
3) The map on the full width of the screen
4) Fixed z-index issue
5) Added functionality to prevent one finger touch scroll
6) Added functionality to save filter state on zoom
7) Icons without background (more compact)

### CODE REVIEW

**Review by davojta — APPROVED** [review]
LGTM

**Comment by uniorunr** [comment]
added functionality to prevent one finger touch scroll

**Comment by uniorunr** [comment]
added functionality to save filter state on zoom

**Comment by uniorunr** [comment]
added functionality to save filter state on zoom; icons without background (more compact)

**Review by davojta — APPROVED** [review]
LGTM

**Pull request merged**
